### PR TITLE
pass placeholder, autofocus and spellcheck through to the editor

### PR DESCRIPTION
**Pull request by rlivsey**
Not sure how to test the autofocus, but I've added tests for the other options

### CODE REVIEW

**Comment by bantic** [comment]
:+1: awesome!

**Comment by mixonic** [comment]
To test autofocus I imagine you would need to get the cursor from the window via `getSelection` and assert its location. A pain. Usually if something is a pain we try to make a helper so it isn't a pain for anyone else in the future :-p

Nice work!

**Comment by rlivsey** [comment]
Cool, I'll work on a test & helper and submit another pull request with that shortly - probably Friday as I'm doing client work all tomorrow

**Comment by bantic** [comment]
@rlivsey Here's a [place where we used `document.activeElement` to check autofocus](https://github.com/aptible/dashboard.aptible.com/blob/e2df50c16c71733f97eb7ef57a0147ac8ab46627/tests/unit/components/handle-input/component-test.js#L134-L140). Might be useful.

**Pull request merged**
